### ISSUE TITLE
XenBlog and the latest version MySQL

### ISSUE THREAD

**Issue by jenokizm** [Audentio/xfaddon-issues#18]
Installing the plugin works on MySQL 5.5.x and MariaDB 10.1.x, but but it does not work on MySQL 5.6.35 or later (especially at MySQL 5.7). I have attached the full text, and errors screen (and incompatible not only with the request, but also with some other).
[XenBlogerror1.zip](https://github.com/Audentio/xfaddon-issues/files/754824/XenBlogerror1.zip)

> Mysqli prepare error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near...

**Comment by ellisonpatterson** [comment]
Hmmm this seems to be a bug with the installer but I've been doing full development with the installer on MariaDB 10.1.22 for a bit now without issue.
