### ISSUE TITLE
Like Threads - Missing Images

### ISSUE THREAD

**Issue by dprock** [Audentio/xfaddon-issues#20]
No images are to be seen in this plugin, I have looked through every folder with no luck. A screenshot is included which shows broken links.

https://gyazo.com/4346426b717a1a018d16400f42a76882

**Comment by ellisonpatterson** [comment]
Could you get the source of the image so we know where it's trying to find the images at and see if they are in the xfaddons repo?

**Comment by JakeBooher** [comment]
They're there, see #14

**Comment by ellisonpatterson** [comment]
Wait I recoded the addon to allow for images to load in style properties.
