### ISSUE TITLE
[TH] Like Threads – post #1131625

### ISSUE THREAD

**Issue by JakeBooher** [Audentio/xfaddon-issues#22]
[Nudaii](https://xenforo.com/community/members/nudaii.14622/) wrote: ([view on xenforo.com](https://xenforo.com/community/threads/th-like-threads-paid.97764/#post-1131625))

> just a note when this is active the default sorting order for forums is broken on latest version of xf, it doesnt respect the selection made in node manager

**Comment by ellisonpatterson** [comment]
Unable to reproduce.

**Comment by mikecreuzer** [comment]
@ellisonpatterson you should follow-up on that thread that Jake posted.

**Comment by ellisonpatterson** [comment]
@mikecreuzer doing now!
