### ISSUE TITLE
[TH] Invitation –  is it possible to add comma separated emails to send to a list of people at once?

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xfaddon-issues#28]
<issue summary>

-------------------------

[HannahKang](https://xenforo.com/community/members/hannahkang.131515/) wrote: ([view on xenforo.com](https://xenforo.com/community/threads/th-invitation-paid.100846/page-5#post-1129117))

> is it possible to add comma seperated emails to send to a list of people at once?

**Comment by ellisonpatterson** [comment]
https://gyazo.com/6cef25a7f0dc10d6a606b2a18d91fa37
