### ISSUE TITLE
[TH] Invitation – post #1135084

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xfaddon-issues#29]
<issue summary>

-------------------------

[DieselMinded](https://xenforo.com/community/members/dieselminded.93/) wrote: ([view on xenforo.com](https://xenforo.com/community/threads/th-invitation-paid.100846/page-5#post-1135084))

> Im using [AD] Invitations, appear to have permissions set correctly but invite link wont show in the drop down unless user visits the invite page first

**Comment by ellisonpatterson** [comment]
This is intended and has been explained before in the thread (to save database space).
